### ISSUE TITLE
function names not displayed in .gph/.xml file

### ISSUE THREAD

**Issue by mohamed** [svenvh/pntools#1]
In the generated .gph/.xml files, the process names are displayed as "ND_0", "ND_1", etc. as generated by pn. In csdf-rtschedtools, it would be very desirable to see the actual function name rather than process name (e.g., "src" instead of "ND_0" and "filter" instead of "ND_1"). One way to resolve this issue is to add a field in the .gph file called "function". This field might look like this:

```
node:
    id:0
    name:ND_0
    function:src
    length:1
```

In case there are multiple functions associated with a process, then the field looks like this:

```
    function:src,filter1,filter2
```

**Comment by svenvh** [comment]
I pushed ba053330344fb4e3fb1cee38c72a61a1610d3c22 which adds the function field to the .gph output.

**Comment by mohamed** [comment]
Thanks Sven! 
mohamed/csdf-rtschedtools has been also updated to reflect the new format. See commit mohamed/csdf-rtschedtools@f1fd3d6a9895fac67494caf6cfc8a073545cce86
